# Generated by Django 3.2 on 2021-05-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="teacher_the_creater",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="DB.teachers"
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="day_to_do",
            field=models.DurationField(
                verbose_name="Количество времени на выполнение задания"
            ),
        ),
        migrations.CreateModel(
            name="HomeworkResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solution",
                    models.CharField(max_length=100, verbose_name="Решение задания"),
                ),
                (
                    "author",
                    models.CharField(max_length=100, verbose_name="Автор задания"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DB.homework"
                    ),
                ),
            ],
        ),
    ]
