# Generated by Django 3.2 on 2021-05-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20210503_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkresult',
            name='author',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='DB.student', verbose_name='Автор задания'),
        ),
    ]
